n = input('Digite algo:')
print(type(n))
print('Só espaços? {}'.format(n.isspace()))
print('É número? {}'.format(n.isnumeric()))
print('É alfabético {}'.format(n.isalpha()))
print('É alfanumérico? {}'.format(n.isalnum()))
print('Está em letras maiúsculas? {}'.format(n.isupper()))
print('Está em letras minúsculas? {}'.format(n.islower()))
print('Está capitalizada? {}'.format(n.istitle()))