frase = 'Curso em Vídeo Python'
frase2 = '   Aprenda Python  '
dv = frase.split()
print(frase[9:20])
print(frase[9:21:2])
print(frase[:5])
print(frase[15:])
print(frase[9::3])
print(len(frase))
print(frase.count('o',0,13))
print(frase.find('deo'))
print(frase.find('Android'))
print(frase.replace('Python','Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase2.strip())
print(frase2.rstrip())
print(frase2.lstrip())
print(frase.split())
print('-'.join(frase))
print(frase.count('o',0,13))
print(frase.count('o'))
print('Python'in frase)
print(frase.lower().find('python'))
print(dv[0])
print(dv[0][3])
